version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./static/uploads:/app/static/uploads
    environment:
      - FLASK_ENV=production
